name: First Test Workflow
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  first-job:
    # runner, # runs-on is reserved keyword
    runs-on: ubuntu-latest
    steps: # requres kvp
      - name: Print greeting
        run: echo "Hello World"
      - name: Print goodbye
        run: echo "Done, goodbye"
        

    
